#!/bin/bash
# Filemux service
# chkconfig: 345 20 80
# description: Filemux service
# processname: filemux

NAME=filemux
DESC="Filemux service"

DAEMON_PATH=/usr/local/bin/filemux
DAEMONOPTS="run -c /usr/local/etc/filemux.yml"
DAEMON_USER=filemux
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
start)
    printf "%-50s" "Starting $NAME..."

    PID=$(su - $DAEMON_USER -c "nohup $DAEMON_PATH $DAEMONOPTS > $LOGFILE 2>&1 & echo \$!")
    if [ -z $PID ]; then
        printf "%s\n" "Fail"
    else
        echo $PID > $PIDFILE
        printf "%s\n" "Ok"
    fi
;;
status)
    printf "%-50s" "Checking $NAME..."

    if [ -f $PIDFILE ]; then
        PID=$(< $PIDFILE)
        if [ -z "$(ps axf | grep ${PID} | grep -v grep)" ]; then
            printf "%s\n" "Process dead but pidfile exists"
        else
            echo "Running"
        fi
    else
        printf "%s\n" "Service not running"
    fi
;;
stop)
    printf "%-50s" "Stopping $NAME"

    PID=$(< $PIDFILE)
    if [ -f $PIDFILE ]; then
        kill -TERM $PID
        printf "%s\n" "Ok"
        rm -f $PIDFILE
    else
        printf "%s\n" "pidfile not found"
    fi
;;
restart)
  	$0 stop
  	$0 start
;;
*)
    echo "Usage: $0 {status|start|stop|restart}"
    exit 1
esac
